{{- template "common.deployment" (list . "activiti.query.deployment") -}}
{{- define "activiti.query.deployment" -}}
spec:
  template:
    spec:
      initContainers:
      {{- if .Values.postgres.enabled }}
        - name: wait-for-postgresql
          image: {{ .Values.init.container.image | quote }}
          imagePullPolicy: {{ .Values.init.container.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ .Release.Name }}-{{ .Values.postgres.name }} {{ .Values.postgres.port }}; do
                  sleep 2;
              done;
              echo 'PostgreSQL OK ✓'
      {{- end }}
      {{- if .Values.init.liquibase.enabled }}
        - name: liquibase
          image: {{ .Values.init.liquibase.image | default .Values.image.repository }}:{{ .Values.init.liquibase.tag | default .Values.image.tag }}
          imagePullPolicy: {{ .Values.init.liquibase.imagePullPolicy }}
          args:
            {{ toYaml .Values.init.liquibase.args | nindent 12 }}
          env:
          {{- if .Values.postgres.enabled }}
            - name: SPRING_DATASOURCE_URL
            {{- if .Values.postgres.uri }}
              value: {{ tpl .Values.postgres.uri $ | quote }}
              {{- else }}
              value: "jdbc:postgresql://{{ .Release.Name }}-{{ .Values.postgres.name }}:{{ .Values.postgres.port }}/postgres"
            {{- end }}
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: {{ default "org.postgresql.Driver" .Values.postgres.driver | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ default "postgres" .Values.postgres.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
            {{- if .Values.postgres.password }}
              value: {{ .Values.postgres.password | quote }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.postgres.name }}
                  key: postgresql-password
             {{- end }}
          {{- else }}
            {{- if .Values.db.uri }}
            - name: SPRING_DATASOURCE_URL
              value: {{ tpl .Values.db.uri $ | quote }}
            {{- end }}
            {{- if .Values.db.driver }}
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: {{ .Values.db.driver | quote }}
            {{- end }}
            {{- if .Values.db.username }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.username | quote }}
            {{- end }}
            {{- if .Values.db.password}}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.password | quote }}
            {{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- end }}
{{- end -}}
