name: 'Setup updatebot'
description: 'Set up a specific version of updatebot and add it to the PATH.'
inputs:
  version:
    description: 'Version of updatebot'
    required: false
    default: 1.1.60
runs:
  using: "composite"
  steps:
    - run: |
        curl -fsSLo updatebot.jar \
          https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/$UPDATEBOT_VERSION/updatebot-$UPDATEBOT_VERSION.jar
        echo "java -jar /usr/local/bin/updatebot.jar \$@" > updatebot
        chmod +x updatebot
        sudo mv updatebot* /usr/local/bin/
        echo updatebot $(updatebot version)
      shell: bash
      env:
        UPDATEBOT_VERSION: ${{ inputs.version }}
