inputs:
  version:
    description: 'Version of updatebot'
    default: 1.1.60
runs:
  using: composite
  steps:
    - run: |
        curl -fsSLo updatebot.jar \
          https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/$UPDATEBOT_VERSION/updatebot-$UPDATEBOT_VERSION.jar
        echo "java -jar /usr/local/bin/updatebot.jar \$@" > updatebot
        chmod +x updatebot
        sudo mv updatebot* /usr/local/bin/
        echo updatebot $(updatebot version)
      env:
        UPDATEBOT_VERSION: ${{ input.version }}
