apiVersion: v1
description: A Helm chart for Activiti Cloud Modeler
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: activiti-cloud-modeling
version: 1.1.8
