name: 'Setup Rancher CLI'
description: 'Set up a specific version of Rancher CLI and add it to the PATH.'
inputs:
  version:
    description: 'Version of Rancher CLI'
    required: false
    default: 2.4.10
  access-key:
    description: 'Rancher API access key'
    required: false
  secret-key:
    description: 'Rancher API secret key'
    required: false
  url:
    description: 'Rancher URL'
    required: false
  context:
    description: 'Rancher context for kubectl configuration'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        TOOL_VERSION=${{ inputs.version }}
        TOOL_NAME=rancher
        TOOL_REPO=rancher/cli
        TOOL_OS=$(uname | tr '[:upper:]' '[:lower:]')
        TOOL_ARCH=amd64
        curl -fsSL https://github.com/$TOOL_REPO/releases/download/v$TOOL_VERSION/$TOOL_NAME-$TOOL_OS-$TOOL_ARCH-v$TOOL_VERSION.tar.gz \
          | tar xz --strip=2 ./$TOOL_NAME-v$TOOL_VERSION/$TOOL_NAME
        sudo mv $TOOL_NAME /usr/local/bin/
        echo $($TOOL_NAME --version)
      shell: bash
    - run: |
        RANCHER2_BEARER_TOKEN=${{ inputs.access-key }}:${{ inputs.secret-key }}
        RANCHER2_URL=${{ inputs.url }}
        if [[ -n "$RANCHER2_BEARER_TOKEN" ]]
        then
          RANCHER_SYSTEM_CONTEXT_INDEX=$(echo 1 | rancher login $RANCHER2_URL -t $RANCHER2_BEARER_TOKEN | grep local | grep System | cut -d ' ' -f1)
          echo $RANCHER_SYSTEM_CONTEXT_INDEX | rancher login $RANCHER2_URL -t $RANCHER2_BEARER_TOKEN > /dev/null
        fi
      shell: bash
    - run: |
        KUBECONTEXT="${{ inputs.context }}"
        if [[ -n "$KUBECONTEXT" ]]
        then
          mkdir -p $HOME/.kube && rancher cluster kubeconfig ${{ inputs.context }} > $HOME/.kube/config
        fi
      shell: bash
