github:
  organisations:
    - name: activiti
      repositories:
        - name: activiti-cloud-full-chart
          branch: master
          useSinglePullRequest: true
    - name: alfresco
      repositories:
        - name: alfresco-process-parent
          branch: develop
          useSinglePullRequest: true
        - name: alfresco-process-application-oracle-kafka
          useSinglePullRequest: true
