github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-example-chart-modeling
      useSinglePullRequest: true
    - name: activiti-cloud-example-chart
      useSinglePullRequest: true
    - name: activiti-cloud-full-chart
      useSinglePullRequest: true
