name: 'Setup jx-release-version'
description: 'Set up a specific version of jx-release-version and add it to the PATH.'
inputs:
  version:
    description: 'Version of jx-release-version'
    required: false
    default: 2.2.3
runs:
  using: "composite"
  steps:
    - run: |
        curl -fsSL https://github.com/jenkins-x-plugins/jx-release-version/releases/download/v$JX_RELEASE_VERSION_VERSION/jx-release-version-linux-amd64.tar.gz \
          | tar xz jx-release-version
        sudo mv jx-release-version /usr/local/bin/
        echo jx-release-version $(jx-release-version --version)
      shell: bash
      env:
        JX_RELEASE_VERSION_VERSION: ${{ inputs.version }}
