inputs:
  version:
    description: 'Version of jx-release-version'
    default: 2.2.3
runs:
  using: composite
  steps:
    - run: |
        curl -fsSL https://github.com/jenkins-x-plugins/jx-release-version/releases/download/v$JX_RELEASE_VERSION_VERSION/jx-release-version-linux-amd64.tar.gz \
          | tar xz jx-release-version
        sudo mv jx-release-version /usr/local/bin/
        echo jx-release-version $(jx-release-version --version)
      env:
        JX_RELEASE_VERSION_VERSION: ${{ input.version }}
