name: 'Setup jx-release-version'
description: 'Set up a specific version of jx-release-version and add it to the PATH.'
inputs:
  version:
    description: 'Version of jx-release-version'
    required: false
    default: 2.2.3
runs:
  using: "composite"
  steps:
    - run: |
        TOOL_VERSION=${{ inputs.version }}
        TOOL_NAME=jx-release-version
        TOOL_REPO=jenkins-x-plugins/$TOOL_NAME
        TOOL_OS=$(uname | tr '[:upper:]' '[:lower:]')
        TOOL_ARCH=amd64
        curl -fsSL https://github.com/$TOOL_REPO/releases/download/v$TOOL_VERSION/$TOOL_NAME-$TOOL_OS-$TOOL_ARCH.tar.gz | tar xz $TOOL_NAME
        sudo mv $TOOL_NAME /usr/local/bin/
        echo $TOOL_NAME $($TOOL_NAME --version)
      shell: bash
      env:
        JX_RELEASE_VERSION_VERSION: ${{ inputs.version }}
