name: 'Setup helm-docs'
description: 'Set up a specific version of helm-docs and add it to the PATH.'
inputs:
  version:
    description: 'Version of helm-docs'
    required: false
    default: 1.4.0
runs:
  using: "composite"
  steps:
    - run: |
        curl -fsSL https://github.com/norwoodj/helm-docs/releases/download/v$HELM_DOCS_VERSION/helm-docs_${HELM_DOCS_VERSION}_linux_x86_64.tar.gz \
          | tar xz helm-docs
        sudo mv helm-docs /usr/local/bin/
        helm-docs --version
      shell: bash
      env:
        HELM_DOCS_VERSION: ${{ inputs.version }}
