name: 'Setup yq'
description: 'Set up a specific version of yq and add it to the PATH.'
inputs:
  version:
    description: 'Version of yq'
    required: false
    default: 3.4.1
runs:
  using: "composite"
  steps:
    - run: |
        TOOL_VERSION=${{ inputs.version }}
        TOOL_NAME=yq
        TOOL_REPO=mikefarah/$TOOL_NAME
        TOOL_OS=$(uname | tr '[:upper:]' '[:lower:]')
        TOOL_ARCH=amd64
        curl -fsSLo $TOOL_NAME https://github.com/$TOOL_REPO/releases/download/$TOOL_VERSION/${TOOL_NAME}_${TOOL_OS}_${TOOL_ARCH}
        chmod +x $TOOL_NAME
        sudo mv $TOOL_NAME /usr/local/bin/
        echo $($TOOL_NAME --version)
      shell: bash
